plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'db/queue_schema.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/**/*'
    - 'config/routes.rb'
    - 'db/migrate/**/*'

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'

Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/**/*'

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false