FROM ruby:4.0.3

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
      build-essential \
      default-mysql-client \
      chromium && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

CMD ["bash", "-c", "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"]